Anthos newsletter 1: Why we chose Anthos
kartverket/skip-docs pull request #34
Opened 2023-10-27 13:16 UTC by esphen

This is the first newsletter in a series of 3 on our new tech blog.

The idea is that we can build on this later to talk about how we use Anthos and our learnings with Anthos in later posts.

Content review much appreciated! 🙂

2023-10-27 13:29 UTC, SnorreSelmer requested changes
Found these typos, other than that it looks very good!

Line 33: "tialing" > "trialing"
Line 64: "assumtions" > "assumptions"

2023-10-27 13:38 UTC, SnorreSelmer approved these changes
:+1:

2023-10-27 13:59 UTC, hustuss reviewed
Just left a minor comment, not sure if I'm too paranoid or not...

2023-10-27 13:59 UTC, hustuss commented on blog/2023-09-11-anthos-1.md
> +organization held at the time, which was "cloud is scary" and "we need to run
Maybe rephrase this to take some sting out of it? Something like "building on the assumptions the organization held at the time, which was that we met our needs through existing infrastructure and had no need for cloud technology"

2023-10-28 00:55 UTC, lislei reviewed
Interesting read Espen - I enjoyed it!

2023-10-28 00:55 UTC, lislei commented on blog/2023-09-11-anthos-1.md
> +This has been something we've worked on for a long time, and still are. After a
```suggestion
This is something we've worked on for a long time, and still are. After a
```

2023-10-28 00:55 UTC, lislei commented on blog/2023-09-11-anthos-1.md
> +manage it from GKE anongside your other clusters.
```suggestion
manage it from GKE alongside your other clusters.
```

2023-10-28 00:55 UTC, lislei commented on blog/2023-09-11-anthos-1.md
> +cluster maintinance easier.
```suggestion
cluster maintenance easier.
```

2023-10-28 00:55 UTC, lislei commented on blog/2023-09-11-anthos-1.md
> +- Ease the maintainance by using the tools that Anthos and Terraform supplies us
```suggestion
- Ease the maintenance by using the tools that Anthos and Terraform supply us
```
supplies is not a verb. Commonly used is to leverage something - perhaps that’s even better here?

2023-10-28 00:55 UTC, lislei commented on blog/2023-09-11-anthos-1.md
> +This newsletter is part of a three-part series newsletter about Anthos in
```suggestion
This newsletter is the first of three part series about Anthos in
```
Avoid repeating of the word newsletter

2023-10-28 00:55 UTC, lislei commented on blog/2023-09-11-anthos-1.md
> +it uses the provider's Kubernetes distribution like AKS, but you can still
I had to look up AKS - perhaps explain that acronym here as well :)

2023-10-30 12:31 UTC, evenh commented on blog/2023-09-11-anthos-1.md
> +In Kartverket we have an ambition to adopt cloud native technologies. There's
```suggestion
At [Kartverket](https://www.kartverket.no/en) we have an ambition to adopt cloud native technologies. There's
```

2023-10-30 12:31 UTC, evenh commented on blog/2023-09-11-anthos-1.md
> +This cloud strategy, however, came too late for us on SKIP. We had already
```suggestion
This cloud strategy, however, came too late for us on <abbr title="Statens Kartverk Infrastructure Platform">SKIP</abbr>. We had already
```

2023-10-30 12:31 UTC, evenh commented on blog/2023-09-11-anthos-1.md
Also consider that the audience may come from sites like news.ycombinator.com, Reddit or other international sites.

2023-10-30 12:31 UTC, evenh commented on blog/2023-09-11-anthos-1.md
> +After some disastrous issues with our previous hybrid cloud PoC, VMWare Tanzu,
As we're calling out a vendor here, maybe share some details on why the experience was bad?

2023-10-30 12:31 UTC, evenh commented on blog/2023-09-11-anthos-1.md
> +it uses the provider's Kubernetes distribution like AKS, but you can still
I think AKS is well known in platform engineering circles.

2023-10-30 12:31 UTC, evenh commented on blog/2023-09-11-anthos-1.md
> +SKIP ran the Anthos PoC over a few months. This took us all the way from
Consider saying something about that this was/is on-prem only and was done in concert with internal network and infrastructure engineers

2023-10-30 12:31 UTC, evenh commented on blog/2023-09-11-anthos-1.md
> +features that came with it. Infrastructure complimented the installation scripts
```suggestion
features that came with it. Infrastructure engineers complimented the installation scripts
```

2023-10-30 12:31 UTC, evenh commented on blog/2023-09-11-anthos-1.md
> +### Anthos Config Managment (ACM)
Is there a dependency on Kustomize, or just the way it was used internally?

2023-10-30 12:31 UTC, evenh commented on blog/2023-09-11-anthos-1.md
> +`port-forward`, `exec` or `run`.
I think we should underline that this has been a painpoint for us, for debuggability.

2023-10-30 12:56 UTC, esphen commented on blog/2023-09-11-anthos-1.md
> +`port-forward`, `exec` or `run`.
I was planning on digging into those issues in the next newsletters :slightly_smiling_face:

2023-10-31 11:34 UTC, esphen commented on blog/2023-09-11-anthos-1.md
> +After some disastrous issues with our previous hybrid cloud PoC, VMWare Tanzu,
That's a whole blog of it's own 😄 I'll redact the name for now

2023-11-06 13:32 UTC, merged